### PR TITLE
Expose DialLogger

### PR DESCRIPTION
**Pull request by wendigo**
Expose new function DialLogger that allows to dial remote syslog server

### CODE REVIEW

**Comment by wendigo** [comment]
I'll be glad for review :)

**Comment by sean-** [comment]
Thanks @wendigo .  I'll merge this as is, but it would be fantastic if you could take the initiative and create a quick unit test for this function (I know there aren't any for this library yet).

**Comment by wendigo** [comment]
Thx @sean-. I've added "create integration test for go-syslog" to my "contribute to OSS" list :) Thx!

**Pull request merged**
