### PR TITLE
Add nacl build tag to unsupported.go

### PR DESCRIPTION
**Pull request by mholt**
This is the last thing keeping us from building Caddy for nacl (not a big deal, but simple enough fix).

### CODE REVIEW

**Comment by mholt** [comment]
(Is this change acceptable? If not, that's fine, just let me know either way.)

**Comment by mholt** [comment]
Pretty please? :smile: I would hate to have to maintain a fork for a diff of 4 bytes.

**Comment by jefferai** [comment]
Seems fine. I'll merge.

**Comment by mholt** [comment]
Yay, thank you!

**Pull request merged**
